version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7.10
        environment:
          NODE_ENV: test
    working_directory: ~/pai-wallet
    steps:
      - checkout  
      - run:
          name: Install npm dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
  deploy:
    docker:
      - image: circleci/node:7.10
        environment:
          NODE_ENV: production
    working_directory: ~/pai-wallet
    steps:
      - run:
          name: Build webpack
          command: npm run build
      - run:
          name: Deploy to Firebase
          command: npm run deploy
workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master


