version: 2
jobs:
  build:
    working_directory: ~/pai-wallet
    docker:
      - image: circleci/node:7.10
    steps:
      - checkout
      - run:
          name: Update npm
          command: 'sudo npm install -g npm@5.5.1'
      - restore_cache:
          key: dependecy-cache-{{ checksum "package.json" }}
      - run: 
          name: Install npm dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:7.10
        environment:
          NODE_ENV: test
    steps:
      - checkout  
      - run:
          name: Run tests
          command: npm run test
  deploy:
    docker:
      - image: circleci/node:7.10
        environment:
          NODE_ENV: production
    steps:
      - run:
          name: Build webpack
          command: npm run build
      - run:
          name: Deploy to Firebase
          command: npm run deploy
workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - build
            - test
          filters:
            branches:
              only: master


