version: 2
jobs:
  build:
    working_directory: ~/pai-wallet
    docker:
      - image: circleci/node:9.3.0
    steps:
      - checkout
      - run:
          name: INSTALL NPM DEPENDENCIES
          command: npm install
      - run:
          name: Checking node modules
          command: |
            pwd
            ls -l
            cd node_modules/
            ls -l
            cd ..
      - run:
          name: BUILD APP
          command: npm run build
  deploy:
    working_directory: ~/pai-wallet
    environment:
      NODE_ENV: production
    docker:
      - image: circleci/node:9.3.0
    steps:
      - checkout
      - run:
          name: Checking node modules
          command: |
            pwd
            ls -l
            cd node_modules/
            ls -l
            cd ..
            echo "showing public folder"
            cd public/
            ls -l
            cd ..
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


