version: 2
jobs:
  build:
    working_directory: ~/pai-wallet
    docker:
      - image: circleci/node:9.3.0
    steps:
      - checkout
      - run:
          name: INSTALL NPM DEPENDENCIES
          command: npm install
      - persist_to_workspace:
          root: ~/pai-wallet
          paths:
           - .
  deploy:
    working_directory: ~/pai-wallet
    environment:
      NODE_ENV: production
      foo: bar
      baz: 123
    docker:
      - image: circleci/node:9.3.0
    steps:
      - attach_workspace:
          at: ./
      - checkout
      - run:
          name: PRINT env variables
          command: echo $NODE_ENV
      - run:
          name: BUILD APP
          command: npm run build
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


