version: 2
jobs:
  build:
    working_directory: ~/pai-wallet
    docker:
      - image: circleci/node:9.3.0
    steps:
      - checkout
      - run:
          name: INSTALL NPM DEPENDENCIES
          command: npm install
      - persist_to_workspace:
          root: ~/pai-wallet
          paths:
           - .
  deploy:
    working_directory: ~/pai-wallet
    environment:
      NODE_ENV: production
      # FIREBASE_API_KEY: $FIREBASE_API_KEY
      # FIREBASE_AUTH_DOMAIN: $FIREBASE_AUTH_DOMAIN
      # FIREBASE_DATABASE_URL: $FIREBASE_DATABASE_URL
      # FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      # FIREBASE_STORAGE_BUCKET: $FIREBASE_STORAGE_BUCKET
      # FIREBASE_MESSAGING_SENDER_ID: $FIREBASE_MESSAGING_SENDER_ID
    docker:
      - image: circleci/node:9.3.0
    steps:
      - attach_workspace:
          at: ./
      # - checkout
      - run:
          name: print env
          command: |
            echo $FIREBASE_DATABASE_URL
            echo $NODE_ENV
            echo $FIREBASE_PROJECT_ID
      # - run:
      #     name: BUILD APP
      #     command: npm run build
      # - run:
      #     name: Deploy to Firebase
      #     command: ./node_modules/.bin/firebase deploy --token=$FIREBASE_DEPLOY_TOKEN
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master


