version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7.10
        environment:
          NODE_ENV: test
    working_directory: ~/pai-wallet
    steps:
      - checkout  
      - run: npm install
      - run: npm run test
workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - test
      # - deploy:
      #   requires:
      #     - test


